# Ruby
# Package your Ruby project.
# Add steps that install rails, analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/ruby

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      sudo apt-get update
      sudo apt-get upgrade
- task: UseRubyVersion@0
  inputs:
    versionSpec: '>= 2.5'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'gem install jquery-rails -v 4.1.1'


- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      gem install bundler
          bundle install --retry=3 --jobs=4
       bundle exec rake


