# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: PowerShell@2 
  inputs:
        targetType: 'inline'
        script: |
          # Write your PowerShell commands here.
          
          Get-NetRoute -AddressFamily IPv4
        errorActionPreference: 'continue'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'Get-NetIPConfiguration'
    errorActionPreference: 'continue'



- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'New-NetIPAddress –IPAddress 192.168.1.0 –PrefixLength 24 –InterfaceAlias “vEthernet (nat)” –SkipAsSource $True'
    errorActionPreference: 'continue'


- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Write your PowerShell commands here.
      
      Get-NetIPAddress -AddressFamily IPv4
    errorActionPreference: 'continue'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'Install-Module -Name Az -AllowClobber -Scope CurrentUser'
    errorActionPreference: 'continue'


- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'Invoke-WebRequest -Uri https://tinyurl.com/um5geuy'


    